name: Deploy to Server

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "PASSWORD=${{ secrets.SSH_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to Server
        run: |
          chmod +x deploy_script.sh
          ./deploy_script.sh
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
